parent_directory: "<path to the parent directory of this repo>" # fill in
working_directory: "dockerfile-flakiness-study/"
input_file: "dataset/shipwright/shipwright_repos.txt"
output_dir: "repositories/"
log_dir: "repositories/"
threads: 5
dockerfiles_dir: "repo_dockerfiles/"
last_commit:
    - 2023 # year
    - 2 # month
    - 23 # day
    - 20 # hour
    - 30 # minute
