end: END
input_inner_dir:
    - part16-1k
    - part17-1k
    - part18-1k
    - part19-1k
    - part20-1k
    - part21-1k
log_file:
    - build16.log
    - build17.log
    - build18.log
    - build19.log
    - build20.log
    - build21.log
output_inner_dir:
    - part16-1k
    - part17-1k
    - part18-1k
    - part19-1k
    - part20-1k
    - part21-1k
start: 15000
