end: 5000
input_inner_dir:
    - part1-1k
    - part2-1k
    - part3-1k
    - part4-1k
    - part5-1k
log_file:
    - build1.log
    - build2.log
    - build3.log
    - build4.log
    - build5.log
output_inner_dir:
    - part1-1k
    - part2-1k
    - part3-1k
    - part4-1k
    - part5-1k
start: 0
