end: 17000
input_inner_dir:
  - part15-1k
  - part16-1k
  - part17-1k
log_file:
  - build15.log
  - build16.log
  - build17.log
output_inner_dir:
  - part15-1k
  - part16-1k
  - part17-1k
start: 14000
