end: 10000
input_inner_dir:
    - part6-1k
    - part7-1k
    - part8-1k
    - part9-1k
    - part10-1k
log_file:
    - build6.log
    - build7.log
    - build8.log
    - build9.log
    - build10.log
output_inner_dir:
    - part6-1k
    - part7-1k
    - part8-1k
    - part9-1k
    - part10-1k
start: 5000
