end: 15000
input_inner_dir:
    - part11-1k
    - part12-1k
    - part13-1k
    - part14-1k
    - part15-1k
log_file:
    - build11.log
    - build12.log
    - build13.log
    - build14.log
    - build15.log
output_inner_dir:
    - part11-1k
    - part12-1k
    - part13-1k
    - part14-1k
    - part15-1k
start: 10000
